### ISSUE TITLE
Can Poly Green Coords extend to 3d?

### ISSUE THREAD

**Issue by fire** [eliemichel/PolyGreenCoords#1]
Reminded by works by pixar: https://graphics.pixar.com/library/ProfileMover/

How applicable is this to 3d polygonal cages?

**Comment by eliemichel** [comment]
You may be interested by *[Green Coordinates for Triquad Cages in 3D](https://research.adobe.com/publication/green-coordinates-for-triquad-cages-in-3d/)* by Thiery and Boubekeur (SIGGRAPH Asia 2022). It is only for straight polygons though, the deformed cage cannot have Bézier arcs like this 2D version has, that's future work. ;) Profile curves are definitly a very nice and related work!

**Comment by fire** [comment]
Thanks, since I don't know where to go from here I'll close the issue for now.

**Comment by fire** [comment]
Do you know if source [Green Coordinates for Triquad Cages in 3D](https://research.adobe.com/publication/green-coordinates-for-triquad-cages-in-3d/) can be released?

**Comment by eliemichel** [comment]
Unlikely, I'd say, unfortunately.

**Comment by fire** [comment]
Seems to be updated in https://github.com/eliemichel/BiharmonicCoords https://dl.acm.org/doi/10.1145/3658208

**Comment by fire** [comment]
Code posted at https://gitlab.com/jthiery/biharmonic3dcoordinates_siggraph2024
